### ISSUE TITLE
Class 'Way\Generators\GeneratorsServiceProvider' not found

### ISSUE THREAD

**Issue by msutyak** [JeffreyWay/Laravel-4-Generators#121]
I have followed the documentation for setting this up, and I am running into issues.  I was able to successfully install the generators on one machine, but now on another I am running into issues after using the generate:resource command.  The files were updated, so it shouldn't be different.  On my localhost server I am seeing the error:  

Class 'Way\Generators\GeneratorsServiceProvider' not found
/Applications/MAMP/htdocs/crowdsets/laravel-master/bootstrap/compiled.php

I have updated my app.php file within app/config to include:
'Way\Generators\GeneratorsServiceProvider'

I added the line: "way/generators": "dev-master"  
to composer.json

When I checked php artisan (when I first installed), everything worked fine, and the generate commands appeared as they should.

Now, typing php artisan gets me:

PHP Fatal error:  Class 'Way\Generators\GeneratorsServiceProvider' not found in /Applications/MAMP/htdocs/crowdsets/laravel-master/bootstrap/compiled.php on line 4121
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Way\Generators\GeneratorsServiceProvider' not found","file":"\/Applications\/MAMP\/htdocs\/crowdsets\/laravel-master\/bootstrap\/compiled.php","line":4121}}

The only thing I changed since installing, was creating a resource using the generate commands:

php artisan generate:resource artist --fields="stage_name=string"

This creates the expected files successfully (except for the test file).  But when I tried to load the site on my new Mac today, it's been giving me these errors.  Both machines are using Mac OS X 10.7.5 and the local server is run through MAMP.  I get the same error when I try to run "php composer.phar update":

 [RuntimeException]  
  Error Output: PHP Fatal error:  Class 'Way\Generators\GeneratorsServiceProv  
  ider' not found in /Applications/MAMP/htdocs/crowdsets/laravel-master/boots  
  trap/compiled.php on line 4121        

 Thank you for your help.

**Comment by akehat** [comment]
What does this mean:

**You also need to point to the fork of the way/generators repo:**

"repositories": [
    {
        "type": "git",
        "url": "git@github.com:jamisonvalenta/Laravel-4-Generators.git"
    }
]

Add those lines to the composer.json?

**Comment by esteficuicci** [comment]
They could solve ? I feel the same tried the various solutions I read but no case

**Comment by pixelspy** [comment]
i have the same problem. it blocks me to generate a key with artisan.
anyone foudn the solution? i'm on it since 2 days...
