### ISSUE TITLE
[Error] FatalErrorException during rollback when migration table name is CamelCase

### ISSUE THREAD

**Issue by JohannesMP** [JeffreyWay/Laravel-4-Generators#170]
When working with `generate:migration`, there is a potential for inconsistent name generation of the migration class causing a `FatalErrorException` during rollbacks.

Please consider the following scenario:
#### 1. Generate a migration that contains CamelCase in the table name:

```
php artisan generate:migration create_UserDetails_table
```
- The resulting migrations file is named:
  **`2013_08_08_175023_create_userdetails_table.php`**
- The resulting migration class in that file is 
  **`CreateUserDetailsTable`**
#### 2. Migration will work:

```
php artisan migrate
Migrated: 2013_08_08_175023_create_userdetails_table
```
#### 3. Rolling back will error out:

(formatted for visual clarity, and Filepath up to the laravel directory shortened to `{ROOT}`)

```
php artisan migrate:rollback
{"error":
    {
    "type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "message":"Class 'CreateUserdetailsTable' not found",
    "file":"{ROOT}\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Migrations\/Migrator.php",
    "line":301
    }
}
```
- This seems to be because the class name is incorrectly generated, compared to what Laravel actually ends up searching for. The `D` in 'Details' is not capitalized because that's what converting `create_userdetails_table`to camelcase should give you.
- This could also be a bug in Laravel. I'm not sure, but it seems like it's just looking at the filename to figure out what the contained class name should actually be.
#### Another quick example:
- input: `create_MyCrazyTableName_table`
- filename: `##...##_create_mycrazycablename_table`
- classname: **`CreateMyCrazyTableNameTable`**
- the class that Laravel looks for during rollback, based on filename: **`CreateMycrazytablenameTable`**
## Fix Suggestions:

The issue is that the filename that is generated, and the Class name are not equivalent.
Here are two possible fixes:

1 - Change the filename to include caps
- input: `create_MyCrazyTableName_table`
- filename: `##...##_create_MyCrazyTableName_table`
- classname: **`CreateMyCrazyTableNameTable`**
- rollback class: **`CreateMyCrazyTableNameTable`**

2 - Generate the class name to correctly match the lowercase filename
- input: `create_MyCrazyTableName_table`
- filename: `##...##_create_mycrazytablename_table`
- classname: **`CreateMycrazytablenameTable`**
- rollback class: **`CreateMycrazytablenameTable`**

I personally prefer option 1, since that makes classes easier to read.

**Comment by Gaaab** [comment]
thank you for saving my life :)
