### ISSUE TITLE
Tabs vs spaces

### ISSUE THREAD

**Issue by taai** [JeffreyWay/Laravel-4-Generators#281]
In my projects I use tabs. I have noticed that the generated files contains spaces in some places, and tabs in other. This inconsistency makes me to replace spaces with tabs manually.

A feature would be option to choose tabs/spaces in the generated files.

Thank you! :+1:

**Comment by instanttim** [comment]
Instead of going one way or the other, if the generator just obeyed .editorconfig wouldn't everyone be happy?
