### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by cskiwi** [JeffreyWay/Laravel-4-Generators#328]
Hi,

When running `php artisan migrate` I get the error off class not found, 
`{"error":"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class '' not found","file":"C:\\wamp\\www\\Project\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator.php","line":297}}`

I've run `composer dump-autoload` didn't help

this started happening, when I deleted everything in my database, and deleted an migration, and added an foreign key in a file, which then I had to rename in order to get it  running in a good order. (forgot to run `php artisan migrate:reset`)

all my migrations are getting loaded (placed `// classname` in each file, and they are outputted in the console before the error is thrown)

**Comment by StevieWunder** [comment]
Composer dump-autoload did the trick for me. Thanks foxted
