### ISSUE TITLE
Can not create migration file

### ISSUE THREAD

**Issue by WilsonFpz** [JeffreyWay/Laravel-4-Generators#365]
Hi,I tried to work with generate:migration but it failed.
It works when typing "php artisan migrate:make create_users_table".
The error message was as following,

[root@www laravel-test]# php artisan generate:migration create_posts_table

  [ErrorException]
  file_put_contents(/root/laravel-test/database/migrations/2014_09_02_072627_create_posts_table.php): faile
  d to open stream: No such file or directory

Any setting I missing?Please help! Many thanks.

**Comment by MartinGacheru** [comment]
same error here pliz assist
