### ISSUE TITLE
"InvalidArgumentException" on "generate:publish-templates"

### ISSUE THREAD

**Issue by Zoomink** [JeffreyWay/Laravel-4-Generators#375]
Hi,

I get the following error when trying to publish templates:

> $ php artisan generate:publish-templates
> [InvalidArgumentException] There are no commands defined in the "config" namespace.

Template files are generated and put into `app\templates`, but they are not used when using scaffolding:

> php artisan generate:scaffold post

Probably because the file `app/config/packages/way/generators/config/config.php` is not created because of the exception.

I am using `"laravel/framework": "4.3.*"` and `"way/generators": "~3.0"`.

**Comment by jahanzebk** [comment]
+1, please fix this, the above solution didn't work for me, publish:config doesn't exist either. changing it to vendor:publish didn't help either.

**Comment by jschlies1** [comment]
Any progress in this issue?????
