### ISSUE TITLE
Can not install with Laravel 5.0

### ISSUE THREAD

**Issue by reinvanleirsberghe** [JeffreyWay/Laravel-4-Generators#384]
I get the following error:

Problem 1
    - Installation request for way/generators ~3.0 -> satisfiable by way/generators[3].
    - Conclusion: remove laravel/framework 5.0.x-dev
    - way/generators 3 requires illuminate/support ~4.0 -> satisfiable by laravel/framework[4.0.x-dev, 4.1.x-dev, 4.2.x-dev], illuminate/support[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, v4.0.0, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.1, v4.0.10, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.13, v4.1.14, v4.1.15, v4.1.16, v4.1.17, v4.1.18, v4.1.19, v4.1.2, v4.1.20, v4.1.21, v4.1.22, v4.1.23, v4.1.24, v4.1.25, v4.1.26, v4.1.27, v4.1.28, v4.1.29, v4.1.3, v4.1.30, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0-BETA1, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8].
    - Can only install one of: laravel/framework[5.0.x-dev, 4.0.x-dev].
    - Can only install one of: laravel/framework[5.0.x-dev, 4.1.x-dev].
    - Can only install one of: laravel/framework[5.0.x-dev, 4.2.x-dev].
    - ...

**Comment by illuminate3** [comment]
pulling up an old issue since this makes the most sense to post here.

Just installed L5 (it's officially out now) and when running the command
```
php artisan route:cache
```

I get this error
```
exception 'BadMethodCallException' with message 'Call to undefined method [package]
```

**Comment by pworld** [comment]
I've installed Laravel 5 in one project. Now, I need to install Laravel 4.2 for other projects. When I tried to running composer update in Laravel 4.2 projects, I've got this error messages:

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework 4.2.x-dev -> satisfiable by laravel/framework[4.2.x-dev].
    - zizaco/entrust dev-master requires illuminate/support ~5.0 -> satisfiable by laravel/framework[5.0.x-dev, 5.1.x-dev], illuminate/support[5.0.x-dev, 5.1.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.4].
    - Can only install one of: laravel/framework[5.0.x-dev, 4.2.x-dev].
    - Can only install one of: laravel/framework[5.1.x-dev, 4.2.x-dev].
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support v5.0.0|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support v5.0.22|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support v5.0.25|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support v5.0.26|don't install laravel/framework 4.2.x-dev
    - don't install illuminate/support v5.0.4|don't install laravel/framework 4.2.x-dev
    - Installation request for zizaco/entrust dev-master -> satisfiable by zizaco/entrust[dev-master].

Any Idea?
Thanks.

**Comment by TheBox193** [comment]
@pworld May want to create a new issue.

**Comment by pworld** [comment]
@TheBox193: I already found the solutions. There's a problem in my package versions. I changed minimum-stability to stable, changed some package versions, and everything works fine. 
Thanks.

**Comment by carolinajimenez26** [comment]
when I run __composer global require "laravel/installer:5.4.*"__
I got the next error:

Problem 1
    - The requested package laravel/installer 5.4 exists as laravel/installer[dev-master, dev-revert-35-master, v1.1.0, v1.1.1, v1.1.2, v1.1.3, v1.2.0, v1.2.1, v1.2.2, v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6, v1.3.7, v1.4.0, v1.4.1] but these are rejected by your constraint.
