### ISSUE TITLE
file_put_contents: failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by cob05** [JeffreyWay/Laravel-4-Generators#394]
Getting the following exception while following along with a Laracasts tutorial:

[ErrorException]  
  file_put_contents(/home/vagrant/code/app1/database/migrations/2014_09_20_194400_create_users_table.php): failed to open stream: No such file or directory

Command:
php artisan generate:migration create_users_table --fields="username(25):string:unique, email:string:unique, password:string(64)"

Using homestead.  Already checked permissions and the vagrant user can write to the folder.  No other problems using the generators for controllers, etc...

Edit: Just noticed that it is missing the 'app' directory under app1(test laravel app name)

Edit 2: Edited config.php under the generators config folder and updated this line to include 'app/':

/**/     'migration_target_path'   => base_path('app/database/migrations'),      /**/

and that worked.

**Comment by cloudEdwards** [comment]
Just to Clarify for any one else having this problem.  This is caused by the config set up for Jeffery Ways generator tools being set for Laravel 5. I am using Laravel 4.2. So for me the config file was here.
    vendor/way/generators/src/config/config.php

All of the generated files are pointing to the wrong places. I changed it to this
```php
 /*
    |--------------------------------------------------------------------------
    | Where the generated files will be saved...
    |--------------------------------------------------------------------------
    |
    */
    'model_target_path'   => app_path(),

    'controller_target_path'   => base_path('app/controllers'),

    'migration_target_path'   => base_path('app/database/migrations'),

    'seed_target_path'   => base_path('app/database/seeds'),

    'view_target_path'   => base_path('app/views')
```

I wrote this comment with out testing until now. And it worked !! Yay!

**Comment by patricpoba** [comment]
thanks guys. it worked work me
