### ISSUE TITLE
How to create post_id instead of id ?

### ISSUE THREAD

**Issue by darkcyber** [JeffreyWay/Laravel-4-Generators#430]
Hello,

By default this generator will create "id" as primary key in the migration file , then i want to ask how to change "id" with something like "post_id" as primary key , so in the migration file only post_id fields and the other not "id","post_id", and the other ?
So is there any way to change default id fields ? or we must change it manually in the migration file ?

Thanks.

**Comment by idhamperdameian** [comment]
"id" is default Laravel primary key convention, if you want change to other, you may define a primaryKey property to override the convention.

**Comment by darkcyber** [comment]
@idhamperdameian Thanks, i just need to create fields for primary key then define in model files for $primaryKey.
