### ISSUE TITLE
BadMethodCallException is coming after run php artisan command

### ISSUE THREAD

**Issue by piyushpatil027** [JeffreyWay/Laravel-4-Generators#433]
Hello , 
         I install Laravel-4-Generators package  successfully but after i run php artisan command it is giving 
exception 'BadMethodCallException' with message 'Call to undefined method [package]' in /usr/share/nginx/html/laravel_new/storage/framework/compiled.php:3561
Can you Solve this bug.
![screenshot from 2014-12-05 15 09 56](https://cloud.githubusercontent.com/assets/6272053/5313632/ceb5fb50-7c90-11e4-815d-086a3eaf7ee8.png)

**Comment by morrislaptop** [comment]
I've developed a method to bridge packages across without modifying their source code, all you need to do is point to a bridging service provider which handles all the differences. Blog article at https://medium.com/@morrislaptop/bridging-laravel-4-packages-to-laravel-5-2081f19643c6 and the source code is at https://github.com/morrislaptop/LaravelFivePackageBridges
