### ISSUE TITLE
Call to undefined method [package]

### ISSUE THREAD

**Issue by affinitycloud** [JeffreyWay/Laravel-4-Generators#436]
When referencing "laravel/framework": "4.2.*" in composer.json I receive a Call to undefined method [package].

If you change the reference to "laravel/framework": "4.2.0" all works fine.

**Comment by morrislaptop** [comment]
I've developed a method to bridge packages across without modifying their source code, all you need to do is point to a bridging service provider which handles all the differences. Blog article at https://medium.com/@morrislaptop/bridging-laravel-4-packages-to-laravel-5-2081f19643c6 and the source code is at https://github.com/morrislaptop/LaravelFivePackageBridges
