### ISSUE TITLE
Generators are posing different directory structure

### ISSUE THREAD

**Issue by joicemjoseph** [JeffreyWay/Laravel-4-Generators#438]
Hi, 
Thank you for taking an initiative to make  an esy to make generator.
I would like to share you an issue on my use.
I generated a Model and it is listing/outputs directly into the root of app(/app/) where routes.php and other files situated instead of putting them in app/models/ . and I am experiencing th same while generating migrations also.
thank you :)

**Comment by JeffreyWay** [comment]
You're using the wrong release. Pull in ~2.0.

**Comment by joicemjoseph** [comment]
Thank you for your comment ..
