### ISSUE TITLE
Generation of Controllers

### ISSUE THREAD

**Issue by cesiztel** [JeffreyWay/Laravel-4-Generators#443]
When I use this great generator package to create a seed, the generator automatically add the suffix "TableSeeder", but when I create a controller I need to write the suffix Controller after the name of the controller that I want to create. I would like to change this behaviour. For instace: php artisan generate:controller User -> generates UserController.php. But I don´t know if might be there are some naming convention issues or some reason to do not do it in this way.
Thanks.

**Comment by JeffreyWay** [comment]
I think it's fine as is.
