### ISSUE TITLE
Any updates for Generators and L5 (as of 2015.01.26 build)

### ISSUE THREAD

**Issue by mikeerickson** [JeffreyWay/Laravel-4-Generators#444]
Seems Generators are broken with the latest L5 build?  I know that the package interface was reworked, not sure if this affects Generators (seems many other packages are working).

@JeffreyWay Any information would be appreciated :-)

**Comment by FrodeMMeling** [comment]
There is a temporary fix here: https://medium.com/@morrislaptop/bridging-laravel-4-packages-to-laravel-5-2081f19643c6
I see that Flash plugin from laracasts was fixed recently. Lets hope this fixed soon.

**Comment by JeffreyWay** [comment]
https://github.com/laracasts/Laravel-5-Generators-Extended
