### ISSUE TITLE
controller generation error in L5

### ISSUE THREAD

**Issue by subdesign** [JeffreyWay/Laravel-4-Generators#448]
If you use _https://github.com/morrislaptop/LaravelFivePackageBridges_ to make Generators package work in Laravel 5, using **generate:controller** fails. There's a quick fix until its officially fixed. Open _ControllerGeneratorCommand.php_ and change:
```php
use Way\Generators\Templates\Data\Controller as ControllerData;
```
to
```php
use Way\Generators\templates\Data\Controller as ControllerData;
```
so make T of Templates part lowercase

**Comment by JeffreyWay** [comment]
This package isn't for L4.

https://github.com/laracasts/Laravel-5-Generators-Extended
