### ISSUE TITLE
L5 and the Generators -- my thoughts

### ISSUE THREAD

**Issue by illuminate3** [JeffreyWay/Laravel-4-Generators#450]
This is 100% speculation and MY OWN personal thoughts.

I have been thinking about this for the past fews day after working with L5.

This package -- as is -- is no longer needed. Within php artisan you already have a majority of way-generators. The parts that are missing are what I miss most -- the RAD code that was laid out fro you by scaffolding. This saved me so much time! If you watch Laracast videos yoiu notice that Jeffery has PHPStorm setup so that he can auto-generate lots of what his generators used to do.

Is this package going to be updated?
I have no idea. I am not in the loop. However, I have a feeling that the php artisan command is just gonna get better rather than this package.

What are our alternatives?
I've seen that bridge package pop up. Great but but! is this really a long term solution or just a bandage for what is still in L4 and possibly will stay that way? I've seen lots of good L3 bundles never move on, I have a feeling that many of the early days great L4 packages are going to start to age and never regenerate into L5 packages. That is awesomeness of github. Anybody can fork the code and go from there. Am I saying to fork this package? No! That is not why I've written this book!

What should we do? What can we do?
My idea is that we start getting gists and templates together that are/were essentially the scaffolding brains. Another possibility would be is help the way-generators evolve to just an extension on the php artisan make commands which essentially be adding a scaffold ability and a way to take those gists/templates to create the RAD stuff that a lot of us use.

What are your thoughts?

**Comment by slayerfat** [comment]
some commands, like generate:seed are not present in artisan (as far as i know), which means that yes, this generator can be useful.

my thoughts?

update this to L5 leaving the generators OR

remove the duplicated generators and leave the scaffold, and other utilities OR

make snippet gists, or a repo full of snippets gists, however, that would mean adapting each snippet to a particular editor

**Comment by illuminate3** [comment]
Taylor has been adding to the functionality of artisan so definitely removing duplicated functionality and supplementing artisan seems to be the way to go.

**Comment by PatrickBauer** [comment]
I'd really like to see a new version for scaffolding and maybe some other extras.

**Comment by JeffreyWay** [comment]
L5 generators.

https://github.com/laracasts/Laravel-5-Generators-Extended
