### ISSUE TITLE
 Error: Class not found on migration

### ISSUE THREAD

**Issue by ghost** [JeffreyWay/Laravel-4-Generators#5]
Hi Jeffrey, when generating a migration e.g: `php artisan generate:migration create_releases_table`

The migration is created but for some reason the class name is being set wrong (compared to your videos on tutsplus premium + the video in the github description).

It is Pascal Casing the class name. This is then a problem as it’s looking for underscores when running `php artisan migrate` which it cant find

So for example it is creating:

class CreateReleasesTable extends Migration {
//stuff
}

Then on migrate it throws the error:

`<abbr title="Symfony\Component\HttpKernel\Exception\FatalErrorException">FatalErrorException</abbr>: Error: Class 'CreateReleasesTable' not found in /home/{dir}/public_html /vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php line 290`

The above issue occurs for me when generating a simple migration and when using the --fields flag.

I also just tried editing the generated file class name to underscores instead but for some reason it still looks for the Pascal case name

p.s I am running PHP Version 5.4.11

**Comment by staviravn** [comment]
Hi Jeff,

Could you please write the full command for generate:migration?

I deleted a migration table and now I get class not found error.

Thanks
