### ISSUE TITLE
Feature Request: Set a field as an ENUM.

### ISSUE THREAD

**Issue by lukearmstrong** [JeffreyWay/Laravel-4-Generators#70]
If I figure out how to do this, I'll submit a PR.

Does this look like how you would expect to create an ENUM?

```
artisan generate:scaffold student --fields="forename:string, surname:string, gender:enum['Male','Female']"
```

**Comment by christoferd** [comment]
In my experience it has been much easier to keep the command line options simple, and update the migration file manually.
